### ISSUE TITLE
Please create a new release

### ISSUE THREAD

**Issue by lukebakken** [ferd/recon#102]
If you have time, would you mind creating a new release? I'm doing some RabbitMQ debugging and am running into the issue fixed by https://github.com/ferd/recon/pull/100. We're pinned to version 2.5.2 in the RabbitMQ codebase. Thank you!

**Comment by ferd** [comment]
Yeah I'll try to do that this week. I have to catch up on OSS stuff, but holiday prep and work has taken all my free energy for this stuff.

**Comment by lukebakken** [comment]
Thanks! It's not the end of the world because we can pin to the most recent commit, too. Merry Christmas!

**Comment by ferd** [comment]
Done, and I switched us to brand new modern ex_doc for all docs and sites as well!

**Comment by lukebakken** [comment]
That's great, thank you! 🎄 🎅
