### ISSUE TITLE
Custom formatters for tracer

### ISSUE THREAD

**Issue by iilyak** [ferd/recon#23]
It would be nice to support custom `formatter` callback function. Custom formatters are useful for log/replay testing. For example if you have an http server you would be able to trace calls to it and format trace records as `curl` or `httpie` commands. Then you can just copy paste wget commands to create simple test case. Custom formatters also would benefit elixir/LFE/... users.

**Comment by ferd** [comment]
Noted. I have an idea of how this could be made to work, but I need to think about it some more.
