### ISSUE TITLE
problem with R15B, badarg when register recon_trace_tracer

### ISSUE THREAD

**Issue by suexcxine** [ferd/recon#25]
$ erl -pa ebin
Erlang R15B (erts-5.9) [source] [smp:4:4] [async-threads:0] [kernel-poll:false]

Eshell V5.9  (abort with ^G)
1> recon_trace:calls({queue, '_', '_'}, 100).
0
2> recon_trace:calls({queue, '_', '_'}, 100).
** exception error: bad argument
     in function  register/2
        called as register(recon_trace_tracer,<0.37.0>)
     in call from recon_trace:setup/2 (src/recon_trace.erl, line 366)
     in call from recon_trace:calls/3 (src/recon_trace.erl, line 300)
3> 

I tried to add unregister before register and problem is solved, 
but I wonder why didn't the clear() in function setup/2 take effect.

I tried r17.3 and no problem.

Any Idea will be appreciated.

**Comment by ferd** [comment]
The only reason I could see this happen would be if unregistration takes a while to happen, after the process died. If that happens and the polling in `wait_for_death/1` (https://github.com/ferd/recon/blob/master/src/recon_trace.erl#L556-L563) returns, I guess there's the possibility that the next function is called and tries to register before that takes place.

Could you try the following function definitions in R15 in recon and tell me if it fixes it:

```erlang
maybe_kill(Name) ->
    case whereis(Name) of
        undefined ->
            ok;
        Pid ->
            unlink(Pid),
            exit(Pid, kill),
            wait_for_death(Pid, Name)
    end.

wait_for_death(Pid, Name) ->
    case is_process_alive(Pid) orelse whereis(Name) =:= Pid of
        true ->
            timer:sleep(10),
            wait_for_death(Pid);
        false ->
            ok
    end.
```
This one should check both for a registration change and the pid dying before returning, and I guess this would fix things in R15B

**Comment by suexcxine** [comment]
I tried your code and fixed successfully.
I believe that you are correct, unregistration when process dies is not atomic.
is_process_alive/1 returns false while that pid is still in registry.
Is this a bug of R15B?

**Comment by ferd** [comment]
No idea. I'll try to patch it tomorrow.

**Comment by ferd** [comment]
Fixed in master.
