### ISSUE TITLE
Does script/app_deps.erl works with rebar3? especially when compiled under different profile?

### ISSUE THREAD

**Issue by linearregression** [ferd/recon#37]

**Comment by ferd** [comment]
It doesn't. Paths would need to be updated to work with it.

**Comment by ferd** [comment]
I just fixed things in master to work for it under the `default` profile.

**Comment by ferd** [comment]
I'll mark this as closed, since rebar3 still fetches all common deps in `default`. If another profile is really needed we can reopen this.
