### ISSUE TITLE
2.3.0 tag/release

### ISSUE THREAD

**Issue by michalwski** [ferd/recon#41]
In the README.md file I can see version 2.3.0 but there is no such tag. When can we expect it?

**Comment by ferd** [comment]
I should probably cut it soon. The 2.3.0 there is the CHANGELOG I've been maintaining that should only be in master

**Comment by ferd** [comment]
I've tagged 2.3.0. I do not own the hex repo for it apparently so I cannot update that. I'll try to get the docsite updated soon enough.

**Comment by michalwski** [comment]
Thanks a lot! Should I close the ticket, or you close it when doc are updated?

**Comment by ferd** [comment]
I'll close when docs are in place :)

**Comment by ferd** [comment]
Docs has been pushed.
