### ISSUE TITLE
Hex.pm package not usable

### ISSUE THREAD

**Issue by eproxus** [ferd/recon#43]
The Hex.pm package for Recon is not usable as a dependency (at least not in Elixir). Using the suggested dependency `{:recon, "~> 2.3"}` yields the following error when building:

```
Could not compile :recon, no "mix.exs", "rebar.config" or "Makefile" (pass :compile as an option to customize compilation, set it to "false" to do nothing)
```

**Comment by ferd** [comment]
You should add the option `:manager` and set it to `:rebar3` in mix I believe. See http://elixir-lang.org/docs/stable/mix/Mix.Tasks.Deps.html

**Comment by eproxus** [comment]
If I do that, I cannot publish my own package:

```
$ mix hex.publish
** (Mix) Can't build package when :manager is set for dependency recon, remove `manager: ...`
```

**Comment by ferd** [comment]
Then I do not know. I am not a mix user at all and don't know what these rules do and whatnot. I'm not quite sure what needs doing, but the problem is something I'd report up to the people maintaining mix?

**Comment by eproxus** [comment]
Apparently some defaults have changed in Elixir 1.3.0 which makes this work again. I wouldn't bother doing anything at this point. This means that Recon as a Hex package depends on Mix 1.3.0 or higher when used in an Elixir project.

**Comment by ferd** [comment]
Thanks for the information!

**Comment by wojtekmach** [comment]
FYI: `{:recon, "~> 2.3", manager: :rebar3}` worked for me on Elixir v1.2.6

**Comment by eproxus** [comment]
@wojtekmach It works if you build it, but not if you want to publish a Hex package.
