### ISSUE TITLE
Is recon:proc_count(memory, 10) an expensive command?

### ISSUE THREAD

**Issue by achowdhury918** [ferd/recon#53]
All,
In my system, I have seen the max simultaneous process number is around 100K.  Will executing recon:proc_count(memory, 10) in every 4 minutes have significant performance impact on the system?
Any suggestion regarding this will be highly appreciated.
Thanks.

**Comment by ferd** [comment]
It won't be free. There will be a cost to the operation and a list of the 100k processes information will need storing (in memory) and traversal. I haven't seen this being too problematic, but if CPU or memory are tightly constrained, it may cause issues, but hopefully not.

**Comment by achowdhury918** [comment]
Thanks a lot, for your reply.

**Comment by ferd** [comment]
Can I consider this issue closed?

Also, if you try the newest release of recon, you should find that the cost for sorting the top results has been greatly reduced thanks to improvements in the underlying sort/select algorithm.
