### ISSUE TITLE
New relase with records tracing

### ISSUE THREAD

**Issue by michalwski** [ferd/recon#68]
I noticed that since version 2.3.6 an interesting feature related to records tracing was merged into master. I'd like to know if or when new release is planned.

**Comment by bartekgorny** [comment]
I just found a minor bug in this feature and submitted a PR, would be nice to have it merged before next release.

**Comment by michalwski** [comment]
Is it PR #69 ?

**Comment by ferd** [comment]
all done

**Comment by michalwski** [comment]
Thanks a lot!
