### ISSUE TITLE
Crash using `binary_memory` on a dead process

### ISSUE THREAD

**Issue by digitalcora** [ferd/recon#95]
`erlang:process_info/2` can return `undefined` — the docs don't explain why, but it's in the typespec and definitely happens when the queried process is dead. If using `recon:info/2` with the `binary_memory` attribute, Recon doesn't handle this return value and crashes in an internal call to `proc_fake` ([see here](https://github.com/ferd/recon/blob/a1736a8e3f9e7f2e3c9a8b672e6cfc720445f558/src/recon.erl#L239)).

Additionally, the typespec for `recon:info/2` doesn't include `undefined` as a possible return value, even though it can return this (e.g. if used on a dead process).

Example in Elixir, because I'm not very good at Erlang syntax, but hopefully it makes sense:

```elixir
pid = spawn(fn -> true end) # spawn a process that immediately dies
Process.sleep(100) # give it a moment to finish
:recon.info(pid, [:binary_memory])
```
```
** (FunctionClauseError) no function clause matching in :recon.proc_fake/2

    The following arguments were given to :recon.proc_fake/2:

        # 1
        [:binary_memory]

        # 2
        :undefined

    (recon 2.5.2) src/recon.erl:247: :recon.proc_fake/2
```

**Comment by ferd** [comment]
See if https://github.com/ferd/recon/pull/115 works; I'm sorry I couldn't get to this better, it was a straightforward fix and the test should be robust enough.

**Comment by digitalcora** [comment]
Thanks @ferd, from our testing so far this issue seems fixed, as long as we handle the possible `undefined`.
